import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import RoundedCorners from "@/app/roundedCorners";
import {ThemeProvider} from "@/components/providers/ThemeProvider";
// import WindowTitleBar from "@/app/windowTitleBar";
import React from "react";
import dynamic from "next/dynamic";
const WindowTitleBar = dynamic(() => import('@/app/windowTitleBar'),
    { ssr: false, loading: loadingProps => <span>loading...</span>}
);

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "DMS NEXT",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <WindowTitleBar />
            <body className={`${inter.className}`}>
                <RoundedCorners>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                </RoundedCorners>
            </body>
        </html>
    );
}
